---
output:
  pdf_document: default
  html_document: default
---
```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(patchwork)
library(GGally)

iris <- read.csv('https://raw.githubusercontent.com/su-mt4007/data/refs/heads/main/IRIS.csv')

iris


# Sepal length gainst petal length
ggplot(iris, aes(sepal_length,petal_length, color = species))+
  geom_point(size = 2)+
  geom_smooth(se = FALSE,method='lm')+
   labs(
    title = "Sepal Length vs Petal Length",
    x = "Sepal Length",
    y = "Petal Length",
    color = 'Species')+
  theme_minimal()

# Sepal width against petal width
ggplot(iris, aes(sepal_width,petal_width, color = species))+
  geom_point(size = 2)+
  geom_smooth(se = FALSE,method='lm')+
   labs(
    title = "Sepal Width vs Petal Width",
    x = "Sepal Width",
    y = "Petal Width",
    color = 'Species')+
  theme_minimal()
```


```{r}
# Species vs Sepal Width
p1 <- ggplot(iris, aes(species,sepal_width,fill= species))+
  geom_boxplot()+
  labs(title = 'Species vs Sepal Width',
       x = 'Species',
       y = 'Sepal Width')+
  theme(axis.text.x = element_text(size = 5), 
  axis.text.y = element_text(size = 5))



# Species vs Sepal Length
p2 <- ggplot(iris, aes(species,sepal_length,fill= species))+
  geom_boxplot()+
  labs(title = 'Species vs Sepal Length',
       x = 'Species',
       y = 'Sepal Length')+
  theme(axis.text.x = element_text(size = 5), 
  axis.text.y = element_text(size = 5))



# Species vs Sepal Width
p3 <- ggplot(iris, aes(species,petal_width,fill= species))+
  geom_boxplot()+
  labs(title = 'Species vs Petal Width',
       x = 'Species',
       y = 'Petal Width',)  +
  theme(axis.text.x = element_text(size = 5), 
    axis.text.y = element_text(size = 5))



# Species vs Petal Length
p4 <- ggplot(iris, aes(species,petal_length,fill= species))+
  geom_boxplot()+
  labs(title = 'Species vs Petal Length',
       x = 'Species',
       y = 'Petal Length') +
  theme(axis.text.x = element_text(size = 5), 
  axis.text.y = element_text(size = 5)) 



(p1|p2)/(p3|p4)

```
```{r}
iris
ggpairs(iris,columns = 1:4,aes(color = species,alpha = 0.5),
        upper = list(continuous = "points"))
```


