---
output:
  pdf_document: default
  html_document: default
---
```{r}
library(dplyr)
library(tidyverse)
library(ggplot2)
library(tidyr)
library(patchwork)
library(GGally)


iris <- read.csv('https://raw.githubusercontent.com/su-mt4007/data/refs/heads/main/IRIS.csv')

head(iris)


# Sepal length gainst petal length
ggplot(iris, aes(sepal_length,petal_length, color = species))+
  geom_point(size = 2)+
  geom_smooth(se = FALSE,method='lm')+
   labs(
    title = "Sepal Length vs Petal Length",
    x = "Sepal Length",
    y = "Petal Length",
    color = 'Species')+
  theme_minimal()

# Sepal width against petal width
ggplot(iris, aes(sepal_width,petal_width, color = species))+
  geom_point(size = 2)+
  geom_smooth(se = FALSE,method='lm')+
   labs(
    title = "Sepal Width vs Petal Width",
    x = "Sepal Width",
    y = "Petal Width",
    color = 'Species')+
  theme_minimal()
```


```{r}
# Species vs Sepal Width
p1 <- ggplot(iris, aes(species,sepal_width,fill= species))+
  geom_boxplot()+
  labs(title = 'Species vs Sepal Width',
       x = 'Species',
       y = 'Sepal Width')+
  theme(axis.text.x = element_text(size = 5), 
  axis.text.y = element_text(size = 5))



# Species vs Sepal Length
p2 <- ggplot(iris, aes(species,sepal_length,fill= species))+
  geom_boxplot()+
  labs(title = 'Species vs Sepal Length',
       x = 'Species',
       y = 'Sepal Length')+
  theme(axis.text.x = element_text(size = 5), 
  axis.text.y = element_text(size = 5))



# Species vs Sepal Width
p3 <- ggplot(iris, aes(species,petal_width,fill= species))+
  geom_boxplot()+
  labs(title = 'Species vs Petal Width',
       x = 'Species',
       y = 'Petal Width',)  +
  theme(axis.text.x = element_text(size = 5), 
    axis.text.y = element_text(size = 5))



# Species vs Petal Length
p4 <- ggplot(iris, aes(species,petal_length,fill= species))+
  geom_boxplot()+
  labs(title = 'Species vs Petal Length',
       x = 'Species',
       y = 'Petal Length') +
  theme(axis.text.x = element_text(size = 5), 
  axis.text.y = element_text(size = 5)) 



(p1|p2)/(p3|p4)

```
```{r, message=FALSE}
iris
ggpairs(iris,columns = 1:4,aes(color = species,alpha = 0.5),
        upper = list(continuous = "points"))
```

```{r}
birds <- read.csv('true.txt')

str(birds)

```



# top 3 vanligaste
```{r, warning=FALSE}
counted_birds <- birds %>% 
  group_by(Artnamn) %>% 
  select(Artnamn,Antal) %>% 
  mutate(Antal = as.numeric(Antal)) %>% 
  summarize(count=sum(Antal,na.rm=TRUE)) %>% 
  arrange(desc(count))
  
head(counted_birds,10)
```
# Månads fördelnnigen
```{r, warning=FALSE, message=FALSE}


prelevent_birds <- birds %>% 
  group_by(Artnamn) %>% 
  mutate(Månad = as.numeric(sapply(strsplit(Startdatum,'-'),`[`, 2),na.rm=TRUE))%>% 
  mutate(Antal = ifelse( is.na(as.numeric(Antal)), NA, as.numeric(Antal))) %>% 
  
  select(Artnamn,Antal,Månad) %>% 
  group_by(Artnamn,Månad) %>% 
  summarize(Antal = sum(Antal,na.rm =TRUE)) %>% 
  filter(Artnamn %in%  c("Grönsiska","Sothöna","Gräsand"))
  

prelevent_birds

ggplot(prelevent_birds, aes(x = Månad, y = Antal, color = Artnamn)) +
  geom_histogram(stat='identity',alpha = 0.5)+
  labs(
    title = "Antal fåglar per månad",
    x = "Månad",
    y = "Antal observationer",
    color = "Artnamn")




```
#rearest birds
```{r}
reareast_birds <- counted_birds %>%
  arrange(count)

head(reareast_birds,20)


```

# Rapportörer som är observerat flest Antal fåglar per tillfälle/ med mest 'tur'.

Not balance in terms of tillfällen per rapportör. 
```{r,warning=FALSE,message=FALSE}

library(knitr)
lucky_watcher <- birds %>% 
  select(Rapportör,Antal,Startdatum) %>% 
  mutate(Antal = ifelse( is.na(as.numeric(Antal)), NA, as.numeric(Antal))) %>% 
  group_by(Rapportör,Startdatum) %>% 
  summarize(Antal = sum(Antal,na.rm=TRUE)) %>%
  ungroup(Startdatum) %>% 
  summarize(Totala_antal_fåglar =  sum(Antal),Dagar = n()) %>% 
  mutate(Fågel_per_dag = round(Totala_antal_fåglar/Dagar,1)) %>% 
  arrange(desc(Fågel_per_dag)) %>% 
  filter(Dagar > 5)


kable(head(lucky_watcher,10),caption = '3')

```
observed bird by the hour during the day.

```{r, warning = FALSE, message=FALSE}
library(hms)

first_digit <- birds %>% 
  select(Rapportör,Antal,Startdatum) %>% 
  mutate(Antal = ifelse( is.na(as.numeric(Antal)), NA, as.numeric(Antal))) %>% 
  group_by(Rapportör,Startdatum) %>%
  filter(!is.na(Antal)) %>% 
  mutate(Antal =first_digit <- as.numeric(substr(as.character(Antal), 1, 1)))
birds


library(dplyr)
library(hms)

by_time <- birds %>%
  select(Artnamn, Starttid, Antal) %>%
  filter(Artnamn %in% c('Grönsiska',"Sothöna","Gräsand") & !is.na(Starttid)) %>%
  mutate(Starttid = as.hms(paste0(Starttid, ":00")),Antal = as.numeric(Antal)) %>%
  filter(!is.na(Antal)  ) %>%
  mutate(Time_Interval = cut(as.numeric(Starttid),   #divide the time into 30min intervals
      breaks = seq(0, 86400, by = 1800), 
      labels = format(seq(
        as.POSIXct("00:00", format = "%H:%M"), 
        as.POSIXct("23:30", format = "%H:%M"), 
        by = "30 mins"), "%H:%M"), 
      include.lowest = TRUE)) %>% 
  group_by(Artnamn,Time_Interval) %>% 
  summarize(count = sum(Antal)) %>% 
  group_by(Artnamn) %>%
  mutate(normalized_count = count / sum(count))

by_time

ggplot(by_time, aes(x = Time_Interval, y = normalized_count, color = Artnamn))+
         geom_bar(stat = 'identity')+
        theme(axis.text.x = element_text(angle = 60, hjust = 1))

# Grönsiska	20211			
# Sothöna	8308			
# Gräsand	7167			
# Storskrake	6750			
# Vitkindad gås	6345			
# Storskarv	5281			
# Björktrast	3173			
# Koltrast	2750			
# Vigg	2375			
# Skrattmås


```

```{r}
by_time_interval <- birds %>%
  select(Starttid, Antal) %>%
  filter(!is.na(Starttid) ) %>%
  mutate(Starttid = as.hms(paste0(Starttid, ":00")),Antal = as.numeric(Antal)) %>%
  filter(!is.na(Antal)  ) %>%
  mutate(Time_Interval = 
      cut(as.numeric(Starttid),   #divides the time into 30min intervals
      breaks = seq(0, 86400, by = 1800), 
      labels = format(seq(
      as.POSIXct("00:00", format = "%H:%M"), 
      as.POSIXct("23:30", format = "%H:%M"), 
      by = "30 mins"), "%H:%M"), 
      include.lowest = TRUE)) %>% 
  group_by(Time_Interval) %>% 
  summarize(count = sum(Antal)) %>% 
  ungroup() %>%
  mutate(norm_count = count/sum(count))

ggplot(by_time_interval, aes(x = Time_Interval, y = norm_count))+
    geom_bar(stat = 'identity')+
    labs(title = 'Observation by time',
         x='Time intervals',
         y="Proportion of observed birds",
         caption = 'figure x')+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

by_time_interval
```


```{r, warning=FALSE}
library(hms)
 birds

by_time <- birds %>%
  select(Starttid, Antal) %>%
  mutate(Antal = ifelse( is.na(as.numeric(Antal)), NA, as.numeric(Antal))) %>%
  mutate(Hour = as.numeric(sapply(strsplit(Starttid,':'),`[`, 1),na.rm=TRUE)) %>% 
  group_by(Hour) %>%
  summarize(Antal = sum(Antal, na.rm=TRUE)) %>% 
  filter(Hour != 'NA')

by_time
```

```{r}
sothöna <- birds %>% 
  filter(Artnamn =='Sothöna') %>% 
  select(Antal,Lokalnamn) %>% 
  mutate(Antal = ifelse( is.na(as.numeric(Antal)), NA, as.numeric(Antal))) %>% 
  print() %>% 
  group_by(Lokalnamn) %>% 
  summarize(count=sum(Antal,na.rm=FALSE)) %>% 
  arrange(desc(count))

kable(head(sothöna,10),caption = 3)

```





