---
title: "Regex HW4"
author: "Sebastian Baarsen"
date: "2024-12-02"
output: html_document
---





```{r}
library(rvest)
base_url <- "https://books.toscrape.com"

names_vector <- c()
ratings_vector <- c()
prices_vector <- c()
books_vector <- c()

for(i in 1:3){
   url <- paste0(base_url,"/catalogue/page-",i,".html")
   html <- read_html(url)
   #collect books
   books <- html %>%
    html_element("ol") %>%
    html_elements("li")

   #collect titles
   names <- books %>%
     html_elements('h3') %>%
     html_elements("a") %>%
     html_attr("title")

   #collect ratings
   ratings <- books %>%
     html_element('p') %>%
     html_attr("class")

   #collect prices
   prices <-  books %>%
     html_nodes('.product_price') %>%
     html_nodes('.price_color') %>%
     html_text
   
   names_vector <- c(names_vector,names)
   ratings_vector <- c(ratings_vector,ratings)
   prices_vector <- c(prices_vector,prices)
   books_vector <- c(books_vector,books)
  
 }

```




```{r}
# collect upc by going in to each books own page
UPC_vec <- c()
for(book in books_vector){
    #collect the url-suffix
    id <-  book %>%
      html_element("h3 a") %>%
      html_attr("href")
    
    #attach url_suffix to url "begining"
    html <- paste0("https://books.toscrape.com/catalogue/",id)

    book_page <- read_html(html)

    #collecting the UPC
    UPC <-  book_page %>%
      html_element('table') %>%
      html_table() %>%
      filter(X1 == "UPC") %>%
      select(X2)
    UPC_vec <- c(UPC_vec,UPC[[1]])
}
  
```

```{r}
library(knitr)
#creat df 


books_df <- data.frame(UPC = UPC_vec,
                       title = names_vector,
                       price= prices_vector,
                       rating = ratings_vector)

finished_books_df <- books_df %>%
  mutate(rating = gsub("star-rating ","",rating))

kable(finished_books_df)
```







