---
output:
  pdf_document: default
  html_document: default
---


Calculate the price per square meter (ppsqm) for each apartment sold. That is, add a new variable to your table containing the data representing the ppsqm.

```{r}
library(dplyr)
library(knitr)
library(ggplot2)
data <- read.csv('Booli_sold.csv')
data <- tibble(data)

```

# 1, Added price per sqauremeter
```{r}
updated_data <- data %>% mutate(ppsqm=soldPrice/livingArea) %>% select(c(1:4),ppsqm,everything())
updated_data
```

# 2, Top 5 expensive (stripped off some variables)
```{r}
sorted_by_price <- updated_data %>% arrange(desc(ppsqm)) %>% select(booliId,soldPrice,c(rent:ppsqm))
df <- head(sorted_by_price,5)
kable(df)
```

# 3, Mean price per square-meter in Ekhagen:
```{r}
mean_ekhagen <- mean(updated_data$ppsqm, na.rm = TRUE) 
mean_ekhagen
```
```{r}
library(ggplot2)
pairs( ppsqm ~  listPrice + rent + livingArea +rooms+ constructionYear+ location.distance.ocean
, data = updated_data,cex = 0.8, cex.labels = 1.2)
```
```{r}
by_date <- updated_data %>%
  mutate(soldDate= as.Date(soldDate))%>%
  arrange(soldDate) %>%
  mutate(soldDate_numeric = dense_rank(soldDate))

```


```{r}
votes <- read.csv("2018_R_per_kommun.csv",sep = ";")
votes <- tibble(votes)
votes

votes %>% arrange(desc(min_rank(KOMMUNKOD)))
```
# 2.1
```{r}
stockholm <- votes %>% filter(LÄNSNAMN == 'Stockholms län')
res <-sum(stockholm$RÖSTER.GILTIGA)

paste("Legitimate votes  in Stockholm:",res,'st')
```

# 2.2, SD have the highest voting percentage in Sjöbo.
```{r}
# (must transform vote-proportion from str to numeric)
by_sd_popularity <- votes %>%
  mutate(M= as.numeric(gsub( ",", ".", SD))) %>%
  arrange(desc(M)) %>%
  select(LÄNSNAMN:FI)


kable(head(by_sd_popularity))
```
# 2,3
```{r,caption = 'hej'}
by_participation <- votes %>% 
  select(LÄNSNAMN:KOMMUNNAMN,VALDELTAGANDE) %>% 
  mutate(VALDELTAGANDE= as.numeric(gsub(',','.',VALDELTAGANDE))) %>% 
  arrange(desc(VALDELTAGANDE))

kable(head(by_participation,3))
```


```{r}
stroke <- read.csv('stroke-data.csv')
stroke
```

```{r}
by_age <- stroke %>% 
  group_by(ever_married) %>%
  summarize(count = n(),strokes = mean(stroke, na.rm = TRUE))

by_age
ggplot(by_age,aes(ever_married,strokes))+
  geom_point(aes(size = count),alpha = 1/2)
  

```
```{r}
by_age <- stroke %>% 
  group_by(age) %>%
  summarize(count = n(),strokes = mean(stroke, na.rm = TRUE)) %>% 
  filter(age>20)

ggplot(by_age,aes(age,strokes))+
  geom_point(aes(size = count),alpha = 1/2) +
  geom_smooth(se=FALSE)
  
```

```{r}
by_work <- stroke %>% 
  filter(work_type %in% c('Private','Self-employed')) %>% 
  group_by(work_type) %>% 
  summarize(n(),strokes = mean(stroke, na.rm = TRUE))
by_work

work_private <- stroke %>% 
  filter(work_type == 'Private')

work_self <- stroke %>% 
  filter(work_type == 'Self-employed' )

```

```{r}
smokeing_data <- stroke %>% 
  filter(smoking_status == "smokes" | smoking_status=="never smoked") %>% 
  mutate(age)

```







